version: "3"

services:
  web:
    container_name: "lamp-apache"
    image: "php:${PHP_VERSION}-apache"
    restart: 'always'
    depends_on:
      - mariadb
    restart: 'always'
    ports:
      - 8080:80
    links:
      - mariadb
    volumes:
      - ./app:/var/www/html
    networks:
      network:
        ipv4_address: 172.19.0.2
  mariadb:
    container_name: "lamp-mariadb"
    image: "mariadb:${MARIADB_VERSION}"
    restart: 'always'
    volumes: 
      - ./mariadb/data:/var/lib/mysql
#      - "./mariadb/logs:${MARIADB_LOG_DIR}"
      - ./mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      network:
        ipv4_address: 172.19.0.3
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp-pma
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      network:
        ipv4_address: 172.19.0.4

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
